# Generated by Django 2.2.4 on 2019-08-20 00:01

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='board.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SteamApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('image', models.TextField(blank=True)),
                ('discount_per', models.PositiveIntegerField(default=0)),
                ('init_price', models.CharField(blank=True, max_length=10)),
                ('final_price', models.CharField(blank=True, max_length=10)),
                ('developer', models.CharField(blank=True, max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('coming_soon', models.BooleanField(default=False)),
                ('release_date', models.CharField(blank=True, max_length=30)),
                ('supported_languages', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('hits', models.PositiveIntegerField(default=0)),
                ('attachment', models.FileField(blank=True, upload_to='attachment/%Y/%m/%d')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(blank=True, max_length=100, null=True)),
                ('app_image', models.TextField(blank=True, null=True)),
                ('app_price', models.CharField(blank=True, max_length=20, null=True)),
                ('app_link', models.CharField(blank=True, max_length=100, null=True)),
                ('app_release_date', models.CharField(blank=True, max_length=30, null=True)),
                ('doc_sort', models.PositiveIntegerField(default=1)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='board.Category')),
                ('recommend', models.ManyToManyField(blank=True, related_name='recommend_doc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doc_sort'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Document')),
            ],
        ),
    ]
