# Generated by Django 2.2.1 on 2019-06-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_document_hit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='hit',
        ),
    ]
