# Generated by Django 2.2.1 on 2019-06-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_document_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
