# Generated by Django 2.2.1 on 2019-06-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20190618_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
