# Generated by Django 2.2.1 on 2019-07-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20190627_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='app_release_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
