# Generated by Django 2.2.1 on 2019-07-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_document_app_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='app_release_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
