# Generated by Django 2.2.1 on 2019-07-02 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0011_auto_20190701_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='recommend',
            field=models.ManyToManyField(blank=True, related_name='recommend_doc', to=settings.AUTH_USER_MODEL),
        ),
    ]
