# Generated by Django 2.2.1 on 2019-07-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_document_recommend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['doc_sort']},
        ),
        migrations.AddField(
            model_name='document',
            name='doc_sort',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
