# Generated by Django 2.2.1 on 2019-07-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20190702_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-doc_sort']},
        ),
    ]
