# Generated by Django 2.2.1 on 2019-07-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_auto_20190702_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
