# Generated by Django 2.2.1 on 2019-07-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_document_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='end_date',
            new_name='end_time',
        ),
    ]
