# Generated by Django 2.2.4 on 2019-08-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_steamapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamapp',
            name='developer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='steamapp',
            name='genre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='steamapp',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='steamapp',
            name='supported_languages',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
